/* =====================================================================
   SWEAT4 – Übungskatalog
   Jede Übung: id, n (Name), g (Muskelgruppe), sub (Zielmuskel), eq (Equipment),
   start (Ausgangsposition), exec (Ausführung), dir (Bewegungsrichtung),
   tips (Technik), errs (häufige Fehler), prim/sec (Muskeln für die 3D-Hervorhebung),
   anim (Bewegungsvorlage der 3D-Engine), alias (alternative Namen für die Zuordnung).

   Neue Übung: einfach einen weiteren Eintrag anhängen. Für anim eine vorhandene
   Vorlage aus uebungen3d.js verwenden (z. B. {t:'press', impl:'db', incline:30}).
   ===================================================================== */
window.SW_MUSKELN = {
  chest: 'Brustmuskel', frontDelt: 'vordere Schulter', sideDelt: 'seitliche Schulter', rearDelt: 'hintere Schulter',
  traps: 'Trapezmuskel (Nacken)', lats: 'Latissimus (breiter Rücken)', upperBack: 'oberer Rücken (Rhomboiden)', lowerBack: 'unterer Rücken (Rückenstrecker)',
  biceps: 'Bizeps', triceps: 'Trizeps', forearms: 'Unterarme', abs: 'gerader Bauchmuskel', obliques: 'schräge Bauchmuskeln',
  glutes: 'Gesäß', quads: 'Quadrizeps (Oberschenkel vorne)', hamstrings: 'Beinbeuger (Oberschenkel hinten)', adductors: 'Adduktoren (Innenseite)',
  abductors: 'Abduktoren (Gesäß seitlich)', calves: 'Waden', hipFlexors: 'Hüftbeuger'
};
window.SW_GRUPPEN = ['Brust', 'Schulter', 'Rücken', 'Beine', 'Bauch', 'Stabilisation', 'Athletik'];
(function () {
  const E = (id, n, g, sub, eq, anim, prim, sec, start, exec, dir, tips, errs, alias) => ({ id, n, g, sub, eq, anim, prim, sec, start, exec, dir, tips, errs, alias: alias || [] });
  const L = [
  /* ---------------- BRUST ---------------- */
  E('schraegbank-kh', 'Schrägbankdrücken mit Kurzhanteln', 'Brust', 'obere Brust', 'Kurzhanteln, Schrägbank (30–45°)', { t: 'press', impl: 'db', incline: 30 }, ['chest', 'frontDelt'], ['triceps'],
    'Rücken flach auf der Schrägbank, Füße fest am Boden, Schulterblätter zusammen und nach unten gezogen. Kurzhanteln über der oberen Brust, Arme fast gestreckt.',
    'Hanteln kontrolliert seitlich neben die obere Brust absenken, bis die Ellbogen etwas unter Bankniveau sind. Danach in einem leichten Bogen wieder nach oben drücken.',
    'Abwärts zur oberen Brust, aufwärts senkrecht über die Schultern – Hanteln oben leicht zueinander.',
    ['Bank auf 30–45° einstellen – höher trainiert mehr Schulter', 'Ellbogen ca. 45–60° vom Körper', 'Handgelenke gerade über den Ellbogen'],
    ['Ellbogen zu weit abgespreizt (90°)', 'Schulterblätter lösen sich von der Bank', 'Hanteln oben zusammenschlagen'], ['Schrägbankdrücken KH', 'Incline Dumbbell Press']),
  E('flachbank-kh', 'Flachbankdrücken mit Kurzhanteln', 'Brust', 'mittlere Brust', 'Kurzhanteln, Flachbank', { t: 'press', impl: 'db' }, ['chest'], ['frontDelt', 'triceps'],
    'Flach auf der Bank, Füße am Boden, leichter natürlicher Bogen im unteren Rücken, Schulterblätter fixiert. Kurzhanteln über der Brust.',
    'Hanteln kontrolliert seitlich neben die Brust absenken, bis eine Dehnung spürbar ist. Kraftvoll nach oben drücken, ohne die Arme ganz durchzustrecken.',
    'Senkrecht über der mittleren Brust auf und ab, oben leicht zueinander.',
    ['Unterarme bleiben senkrecht', 'Tiefer absenken als mit der Langhantel möglich – aber schmerzfrei', 'Ausatmen beim Drücken'],
    ['Hanteln zu weit über dem Gesicht', 'Gesäß hebt von der Bank ab', 'Zu schnelles Absenken'], ['Kurzhantel Bankdrücken', 'Dumbbell Bench Press']),
  E('fliegende-kh', 'Fliegende mit Kurzhanteln', 'Brust', 'Brust (Dehnung, Isolation)', 'Kurzhanteln, Flachbank', { t: 'fly', v: 'db' }, ['chest'], ['frontDelt'],
    'Flach auf der Bank, Kurzhanteln mit neutralem Griff über der Brust, Ellbogen leicht gebeugt und fixiert.',
    'Arme in einem weiten Bogen seitlich öffnen, bis die Ellbogen etwa auf Brusthöhe sind. Dann im selben Bogen wieder zusammenführen – wie eine Umarmung.',
    'Halbkreis seitlich nach unten und wieder nach oben.',
    ['Ellbogenwinkel bleibt während der ganzen Bewegung gleich', 'Nur so tief, wie die Schulter es angenehm zulässt', 'Leichtere Gewichte als beim Drücken'],
    ['Arme strecken oder beugen (wird zum Drücken)', 'Zu tief absenken – Schulterbelastung', 'Gewicht zu schwer'], ['Kurzhantel Fliegende', 'Flys']),
  E('fliegende-schraeg', 'Fliegende auf der Schrägbank mit Kurzhanteln', 'Brust', 'obere Brust', 'Kurzhanteln, Schrägbank', { t: 'fly', v: 'db', incline: 30 }, ['chest'], ['frontDelt'],
    'Rücken an der Schrägbank (30°), Kurzhanteln mit neutralem Griff über der oberen Brust, Ellbogen leicht gebeugt.',
    'Arme im Bogen seitlich öffnen bis zur Dehnung der oberen Brust, dann im Bogen wieder über der Brust zusammenführen.',
    'Halbkreis seitlich nach unten und zurück.',
    ['Schulterblätter bleiben zusammen', 'Ellbogen leicht gebeugt fixieren', 'Oben nicht ablegen – Spannung halten'],
    ['Zu steile Bank', 'Hanteln schwingen', 'Ellbogen sinken unter die Schulter ab'], ['Schrägbank Fliegende']),
  E('ueberzuege-kh', 'Überzüge mit Kurzhantel', 'Brust', 'Brust & Latissimus', 'Kurzhantel, Flachbank', { t: 'pullover' }, ['chest', 'lats'], ['triceps', 'abs'],
    'Rücken auf der Bank, Kurzhantel mit beiden Händen an der Hantelscheibe über der Brust, Arme leicht gebeugt.',
    'Hantel im Bogen hinter den Kopf absenken, bis eine Dehnung in Brust und Latissimus spürbar ist. Dann im gleichen Bogen zurück über die Brust ziehen.',
    'Bogen vom Brustkorb nach hinten über den Kopf und zurück.',
    ['Ellbogenwinkel konstant', 'Rippen unten halten – kein Hohlkreuz', 'Langsam in die Dehnung'],
    ['Arme beugen und strecken', 'Hohlkreuz', 'Zu schweres Gewicht'], ['Pullover', 'Überzüge']),
  E('bankdruecken-lh', 'Bankdrücken mit Langhantel', 'Brust', 'mittlere Brust', 'Langhantel, Flachbank mit Ablage', { t: 'press', impl: 'bar' }, ['chest'], ['frontDelt', 'triceps'],
    'Flach auf der Bank, Augen unter der Stange, Füße fest am Boden. Griff etwas breiter als schulterbreit, Schulterblätter zusammen und nach unten.',
    'Stange aus der Ablage heben, kontrolliert zur unteren/mittleren Brust absenken, kurz berühren und kraftvoll nach oben drücken.',
    'Leicht schräger Weg: unten über der unteren Brust, oben über den Schultern.',
    ['Handgelenke gerade, Stange über den Unterarmen', 'Ellbogen ca. 45–70° vom Körper', 'Ganzkörperspannung, Gesäß bleibt auf der Bank'],
    ['Stange auf der Brust abfedern', 'Ellbogen 90° abgespreizt', 'Gesäß hebt ab'], ['Bankdrücken', 'Bench Press', 'Flachbankdrücken LH', 'Flachbankdrücken']),
  E('schraegbank-lh', 'Schrägbankdrücken mit Langhantel', 'Brust', 'obere Brust', 'Langhantel, Schrägbank', { t: 'press', impl: 'bar', incline: 30 }, ['chest', 'frontDelt'], ['triceps'],
    'Rücken an der Schrägbank (30–45°), Griff etwas breiter als schulterbreit, Schulterblätter fixiert.',
    'Stange kontrolliert zur oberen Brust (unter dem Schlüsselbein) absenken und senkrecht nach oben drücken.',
    'Auf und ab über der oberen Brust.',
    ['Stange berührt die obere Brust', 'Kopf bleibt auf der Bank', 'Ruhige, kontrollierte Wiederholungen'],
    ['Stange zu tief Richtung Bauch', 'Bank zu steil', 'Abfedern'], ['Schrägbankdrücken', 'Incline Bench Press']),
  E('schraegbank-multi', 'Schrägbankdrücken an der Multipresse', 'Brust', 'obere Brust', 'Multipresse, Schrägbank', { t: 'press', impl: 'smith', incline: 30 }, ['chest', 'frontDelt'], ['triceps'],
    'Schrägbank so unter die Multipresse stellen, dass die Stange senkrecht über der oberen Brust läuft. Griff etwas breiter als schulterbreit.',
    'Stange entriegeln, kontrolliert zur oberen Brust absenken und senkrecht nach oben drücken.',
    'Exakt senkrecht – durch die Führung vorgegeben.',
    ['Bankposition vor dem Satz prüfen', 'Sicherheitsanschläge einstellen', 'Schulterblätter zusammen'],
    ['Falsche Bankposition – Stange trifft Hals oder Bauch', 'Ellbogen zu weit außen'], ['Multipresse Schrägbank', 'Smith Machine Incline Press']),
  E('flachbank-multi', 'Flachbankdrücken an der Multipresse', 'Brust', 'mittlere Brust', 'Multipresse, Flachbank', { t: 'press', impl: 'smith' }, ['chest'], ['frontDelt', 'triceps'],
    'Flachbank unter der Multipresse, Stange senkrecht über der mittleren Brust, Griff etwas breiter als schulterbreit.',
    'Stange entriegeln, kontrolliert zur Brust absenken und senkrecht nach oben drücken.',
    'Exakt senkrecht über der mittleren Brust.',
    ['Sicherheitsanschläge auf Brusthöhe einstellen', 'Handgelenke gerade', 'Kontrolliertes Tempo'],
    ['Bank falsch positioniert', 'Abfedern auf der Brust'], ['Multipresse Bankdrücken', 'Smith Machine Bench Press']),
  E('butterfly', 'Fliegende am Butterfly-Gerät', 'Brust', 'Brust (Isolation)', 'Butterfly-Maschine', { t: 'fly', v: 'machine' }, ['chest'], ['frontDelt'],
    'Sitz so einstellen, dass die Oberarme waagerecht auf Schulterhöhe liegen. Rücken an der Lehne, Unterarme bzw. Hände an den Polstern/Griffen.',
    'Polster vor der Brust zusammendrücken, kurz halten und kontrolliert öffnen, bis eine leichte Dehnung entsteht.',
    'Bogen von außen nach vorne zur Körpermitte.',
    ['Schultern tief und hinten', 'Brust raus, Rücken an der Lehne', 'Bewegung aus der Brust, nicht aus den Armen'],
    ['Sitz zu hoch/tief', 'Schultern ziehen nach vorne', 'Gewicht beim Öffnen fallen lassen'], ['Butterfly', 'Pec Deck', 'Butterflymaschine']),
  E('kabel-fliegende-gerade', 'Fliegende am Kabelzug – gerade', 'Brust', 'mittlere Brust', 'Kabelturm (Rollen auf Schulterhöhe)', { t: 'fly', v: 'cable', dir: 'mid' }, ['chest'], ['frontDelt'],
    'Mittig zwischen zwei Kabeltürmen, leichte Schrittstellung, Oberkörper leicht vorgeneigt. Griffe auf Schulterhöhe, Arme seitlich geöffnet und leicht gebeugt.',
    'Griffe in einem waagerechten Bogen vor der Brust zusammenführen, kurz anspannen und kontrolliert öffnen.',
    'Waagerechter Bogen nach vorne zur Körpermitte.',
    ['Ellbogenwinkel bleibt gleich', 'Stabiler Stand', 'Hände treffen sich vor der Brust'],
    ['Zu viel Gewicht – Oberkörper kippt', 'Arme werden zum Drücken gebeugt'], ['Kabelzug Fliegende', 'Cable Fly']),
  E('kabel-fliegende-oben', 'Fliegende am Kabelzug – von oben', 'Brust', 'untere Brust', 'Kabelturm (Rollen oben)', { t: 'fly', v: 'cable', dir: 'high' }, ['chest'], ['frontDelt'],
    'Zwischen den Türmen, Griffe von den oberen Rollen, Schrittstellung, Oberkörper leicht vorgeneigt.',
    'Griffe im Bogen nach vorne-unten vor die untere Brust bzw. den Bauch führen, kurz halten und kontrolliert zurück.',
    'Bogen von oben-außen nach unten-innen.',
    ['Brust bleibt oben', 'Schultern tief', 'Hände treffen sich auf Höhe des unteren Brustbeins'],
    ['Schwung aus dem Oberkörper', 'Schultern ziehen hoch'], ['Cable Crossover', 'Kabelzug von oben']),
  E('kabel-fliegende-unten', 'Fliegende am Kabelzug – von unten nach oben', 'Brust', 'obere Brust', 'Kabelturm (Rollen unten)', { t: 'fly', v: 'cable', dir: 'low' }, ['chest', 'frontDelt'], [],
    'Zwischen den Türmen, Griffe von den unteren Rollen, aufrecht in Schrittstellung, Arme seitlich unten, leicht gebeugt.',
    'Griffe im Bogen nach vorne-oben bis auf Höhe der oberen Brust zusammenführen und kontrolliert absenken.',
    'Bogen von unten-außen nach oben-innen.',
    ['Nicht höher als Kinnhöhe', 'Ellbogen leicht gebeugt fixieren', 'Rippen unten halten'],
    ['Hohlkreuz', 'Arme ziehen statt im Bogen führen'], ['Low Cable Fly', 'Kabelzug von unten']),
  E('dips', 'Dips', 'Brust', 'untere Brust & Trizeps', 'Barren / Dip-Station', { t: 'dips' }, ['chest', 'triceps'], ['frontDelt'],
    'Am Barren gestützt, Arme gestreckt, Schultern tief. Oberkörper leicht nach vorne geneigt, Beine angewinkelt.',
    'Kontrolliert absenken, bis die Oberarme etwa waagerecht sind. Dann kraftvoll nach oben drücken, ohne die Ellbogen zu überstrecken.',
    'Senkrecht nach unten und oben, Oberkörper leicht vorgeneigt.',
    ['Vorneigung betont die Brust, aufrecht den Trizeps', 'Schultern nicht zu den Ohren ziehen', 'Nur so tief, wie die Schulter es zulässt'],
    ['Zu tief – Schulterbelastung', 'Schwingen mit den Beinen', 'Schultern sacken ein'], ['Barrenstütz', 'Dip']),

  /* ---------------- SCHULTER ---------------- */
  E('schulterdruecken-kh', 'Schulterdrücken mit Kurzhanteln – sitzend', 'Schulter', 'vordere & seitliche Schulter', 'Kurzhanteln, Bank mit Lehne', { t: 'ohp', impl: 'db', seated: true }, ['frontDelt', 'sideDelt'], ['triceps', 'traps'],
    'Aufrecht auf der Bank (Lehne fast senkrecht), Rücken an der Lehne. Kurzhanteln auf Schulterhöhe, Handflächen nach vorne.',
    'Hanteln senkrecht über den Kopf drücken, bis die Arme fast gestreckt sind. Kontrolliert zurück auf Schulterhöhe.',
    'Senkrecht nach oben, oben leicht zueinander.',
    ['Rumpf angespannt, kein Hohlkreuz', 'Unterarme bleiben senkrecht', 'Oben nicht zusammenschlagen'],
    ['Rücken löst sich von der Lehne', 'Zu tiefes Absenken mit Schmerz', 'Arme ganz durchdrücken'], ['Kurzhantel Schulterdrücken', 'Dumbbell Shoulder Press']),
  E('schulterdruecken-multi-front', 'Schulterdrücken an der Multipresse – Front – sitzend', 'Schulter', 'vordere Schulter', 'Multipresse, Bank mit Lehne', { t: 'ohp', impl: 'smith', seated: true }, ['frontDelt', 'sideDelt'], ['triceps'],
    'Bank so unter die Multipresse stellen, dass die Stange knapp vor dem Gesicht läuft. Griff etwas breiter als schulterbreit.',
    'Stange von Kinn-/Schlüsselbeinhöhe senkrecht nach oben drücken und kontrolliert zurückführen.',
    'Senkrecht vor dem Gesicht.',
    ['Kopf bleibt an der Lehne – Stange läuft vorbei', 'Sicherheitsanschläge einstellen', 'Ellbogen leicht vor dem Körper'],
    ['Bank zu weit vorne/hinten', 'Hohlkreuz'], ['Multipresse Schulterdrücken', 'Smith Machine Shoulder Press']),
  E('nackendruecken-multi', 'Nackendrücken an der Multipresse – sitzend', 'Schulter', 'seitliche & vordere Schulter', 'Multipresse, Bank', { t: 'ohp', impl: 'smith', seated: true, behind: true }, ['sideDelt', 'frontDelt'], ['triceps', 'traps'],
    'Aufrecht sitzend, Stange läuft hinter dem Kopf. Griff deutlich breiter als schulterbreit.',
    'Stange aus dem Nacken (etwa Ohrhöhe) senkrecht nach oben drücken und kontrolliert bis Ohrhöhe zurück.',
    'Senkrecht hinter dem Kopf.',
    ['Nur mit guter Schulterbeweglichkeit ausführen', 'Nicht tiefer als Ohrhöhe', 'Kopf leicht nach vorne'],
    ['Zu tief in den Nacken', 'Zu schwere Gewichte – Verletzungsrisiko'], ['Nackendrücken Multipresse']),
  E('schulterdruecken-lh-stehend', 'Schulterdrücken mit Langhantel – stehend – Front', 'Schulter', 'vordere Schulter', 'Langhantel', { t: 'ohp', impl: 'bar' }, ['frontDelt', 'sideDelt'], ['triceps', 'abs', 'glutes'],
    'Schulterbreiter Stand, Stange liegt vorne auf den Schultern/Schlüsselbeinen, Griff knapp schulterbreit, Ellbogen leicht vor der Stange.',
    'Stange senkrecht über den Kopf drücken, Kopf dabei kurz zurück und unter die Stange schieben. Kontrolliert zurück zu den Schultern.',
    'Senkrechte Linie über der Fußmitte.',
    ['Gesäß und Bauch fest – kein Hohlkreuz', 'Oben steht die Stange über dem Mittelfuß', 'Knie gestreckt, kein Schwung'],
    ['Stange vor dem Körper drücken', 'Hohlkreuz', 'Schwung aus den Beinen'], ['Military Press', 'Overhead Press', 'Frontdrücken']),
  E('nackendruecken-lh-stehend', 'Nackendrücken mit Langhantel – stehend', 'Schulter', 'seitliche Schulter', 'Langhantel', { t: 'ohp', impl: 'bar', behind: true }, ['sideDelt', 'frontDelt'], ['triceps', 'traps'],
    'Schulterbreiter Stand, Stange im Nacken auf dem Trapez, Griff breit.',
    'Stange von Ohrhöhe senkrecht nach oben drücken und kontrolliert bis Ohrhöhe zurückführen.',
    'Senkrecht hinter dem Kopf.',
    ['Gute Schulterbeweglichkeit nötig', 'Leichtes Gewicht', 'Rumpf stabil'],
    ['Zu tief absenken', 'Kopf weit nach vorne schieben'], ['Nackendrücken']),
  E('seitheben-stehend', 'Seitheben mit Kurzhanteln – stehend', 'Schulter', 'seitliche Schulter', 'Kurzhanteln', { t: 'lateral' }, ['sideDelt'], ['traps', 'frontDelt'],
    'Hüftbreiter Stand, Knie leicht gebeugt, Oberkörper minimal vorgeneigt. Kurzhanteln seitlich am Körper, Ellbogen leicht gebeugt.',
    'Arme seitlich bis auf Schulterhöhe heben – Ellbogen führen, kleine Finger leicht oben. Langsam absenken.',
    'Seitlich nach oben bis Schulterhöhe.',
    ['Nicht höher als Schulterhöhe', 'Schultern tief – nicht zu den Ohren', 'Langsam ablassen'],
    ['Schwung aus dem Oberkörper', 'Zu schweres Gewicht', 'Schultern ziehen hoch'], ['Seitheben', 'Lateral Raise']),
  E('seitheben-sitzend', 'Seitheben mit Kurzhanteln – sitzend', 'Schulter', 'seitliche Schulter', 'Kurzhanteln, Bank', { t: 'lateral', seated: true }, ['sideDelt'], ['traps'],
    'Aufrecht auf der Bankkante, Kurzhanteln seitlich neben dem Körper, Ellbogen leicht gebeugt.',
    'Arme seitlich bis auf Schulterhöhe heben und langsam wieder absenken.',
    'Seitlich nach oben bis Schulterhöhe.',
    ['Sitzend ist Schwung kaum möglich – saubere Isolation', 'Ellbogen führen die Bewegung'],
    ['Hohlkreuz', 'Hände höher als Ellbogen'], ['Seitheben sitzend']),
  E('seitheben-einarmig', 'Seitheben – stehend – einarmig', 'Schulter', 'seitliche Schulter', 'Kurzhantel, Halt (Stange/Gerät)', { t: 'lateral', one: true }, ['sideDelt'], ['obliques', 'traps'],
    'Seitlich neben einer Stange stehen und mit der freien Hand festhalten. Kurzhantel in der äußeren Hand.',
    'Arm seitlich bis Schulterhöhe heben und langsam absenken. Danach Seite wechseln.',
    'Seitlich nach oben bis Schulterhöhe.',
    ['Leichte Neigung zur Stange vergrößert den Bewegungsradius', 'Rumpf stabil halten'],
    ['Oberkörper kippt mit', 'Schwung'], ['Einarmiges Seitheben']),
  E('seitheben-kabel', 'Seitheben am Kabelzug', 'Schulter', 'seitliche Schulter', 'Kabelturm (Rolle unten), Einzelgriff', { t: 'lateral', cable: true, one: true }, ['sideDelt'], ['traps'],
    'Seitlich zum Kabelturm stehen, Griff mit der turmfernen Hand vor dem Körper fassen. Freie Hand an der Hüfte oder am Turm.',
    'Arm seitlich bis auf Schulterhöhe ziehen und langsam zurückführen.',
    'Bogen von vor dem Körper seitlich nach oben.',
    ['Konstante Spannung über den ganzen Weg', 'Ellbogen leicht gebeugt'],
    ['Oberkörper lehnt sich weg', 'Zu schnelles Ablassen'], ['Kabel Seitheben', 'Cable Lateral Raise']),
  E('vorgebeugtes-seitheben', 'Vorgebeugtes Seitheben – hintere Schulter', 'Schulter', 'hintere Schulter', 'Kurzhanteln', { t: 'rearDelt', v: 'db' }, ['rearDelt'], ['upperBack', 'traps'],
    'Hüftbreiter Stand, Knie leicht gebeugt, Oberkörper mit geradem Rücken weit vorgebeugt. Kurzhanteln hängen unter den Schultern.',
    'Arme seitlich nach oben bis auf Rückenhöhe heben, Ellbogen leicht gebeugt. Langsam absenken.',
    'Seitlich nach oben, senkrecht zum Oberkörper.',
    ['Rücken bleibt gerade', 'Bewegung aus der Schulter, nicht durch Schulterblattziehen', 'Leichte Gewichte'],
    ['Rundrücken', 'Schwung mit dem Oberkörper', 'Zu schwer – Rücken übernimmt'], ['Reverse Flys', 'Vorgebeugtes Seitheben']),
  E('vorgebeugt-seitheben-turm', 'Vorgebeugtes Seitheben am Turm', 'Schulter', 'hintere Schulter', 'Kabelturm (Rollen unten)', { t: 'rearDelt', v: 'cable' }, ['rearDelt'], ['upperBack'],
    'Zwischen den Türmen, vorgebeugt mit geradem Rücken. Kabel überkreuzt: linke Hand hält den rechten Griff und umgekehrt.',
    'Arme seitlich nach oben bis auf Rückenhöhe ziehen und kontrolliert zurückführen.',
    'Seitlich nach oben, Kabel kreuzen sich unter dem Körper.',
    ['Konstante Spannung durch das Kabel', 'Ellbogen leicht gebeugt'],
    ['Oberkörper richtet sich auf', 'Schultern ziehen hoch'], ['Reverse Cable Fly']),
  E('vorgebeugt-seitheben-turm-einarmig', 'Vorgebeugtes Seitheben – einarmig am Turm', 'Schulter', 'hintere Schulter', 'Kabelturm (Rolle unten)', { t: 'rearDelt', v: 'cable1' }, ['rearDelt'], ['upperBack'],
    'Seitlich zum Turm, vorgebeugt mit geradem Rücken, Griff mit der turmfernen Hand. Freie Hand stützt sich am Oberschenkel ab.',
    'Arm seitlich bis auf Rückenhöhe ziehen und kontrolliert zurück. Danach Seite wechseln.',
    'Seitlich nach oben-außen.',
    ['Rumpf nicht mitdrehen', 'Langsam ablassen'], ['Oberkörper dreht auf', 'Zu viel Gewicht'], []),
  E('face-pulls', 'Face Pulls', 'Schulter', 'hintere Schulter & Rotatoren', 'Kabelturm (Rolle auf Kopfhöhe), Seil', { t: 'facePull' }, ['rearDelt', 'upperBack'], ['traps', 'biceps'],
    'Vor dem Turm stehen, Seil auf Kopfhöhe mit Obergriff, Arme gestreckt, leicht zurückgelehnt.',
    'Seil Richtung Gesicht ziehen, Ellbogen hoch und nach außen. Am Ende die Hände neben die Ohren drehen (Außenrotation). Kontrolliert zurück.',
    'Waagerecht zum Gesicht, Seilenden auseinander.',
    ['Ellbogen bleiben auf Schulterhöhe oder höher', 'Schulterblätter zusammen', 'Kurz halten'],
    ['Ellbogen sinken ab (wird zum Rudern)', 'Zurücklehnen mit Schwung'], ['Facepull', 'Face Pull']),
  E('hintere-schulter-turm-ueberkreuzt', 'Hintere Schulter am Turm – überkreuzt', 'Schulter', 'hintere Schulter', 'Kabelturm (Rollen auf Schulterhöhe)', { t: 'rearDelt', v: 'cross' }, ['rearDelt'], ['upperBack', 'traps'],
    'Aufrecht zwischen den Türmen, Kabel überkreuzt vor der Brust (linke Hand rechtes Kabel), Arme leicht gebeugt auf Schulterhöhe.',
    'Arme waagerecht nach außen-hinten ziehen, bis sie seitlich ausgestreckt sind. Kontrolliert zurück in die Kreuzung.',
    'Waagerechter Bogen nach außen.',
    ['Arme bleiben auf Schulterhöhe', 'Brust raus, Schultern tief'], ['Hohlkreuz', 'Arme beugen'], ['Reverse Crossover']),
  E('nackenziehen-turm-stange', 'Nackenziehen am Turm mit Stange', 'Schulter', 'seitliche Schulter & Trapez', 'Kabelturm (Rolle unten), gerade Stange', { t: 'uprightRow', impl: 'cable' }, ['sideDelt', 'traps'], ['frontDelt', 'biceps'],
    'Vor dem Turm, Stange mit Obergriff etwa schulterbreit vor den Oberschenkeln, Arme gestreckt.',
    'Stange eng am Körper bis etwa Brusthöhe nach oben ziehen – Ellbogen führen und bleiben über den Händen. Kontrolliert absenken.',
    'Senkrecht nach oben am Körper entlang.',
    ['Nicht höher als Brusthöhe – schont die Schulter', 'Etwas breiterer Griff ist schulterfreundlicher'],
    ['Zu enger Griff', 'Zu hoch ziehen', 'Schwung'], ['Aufrechtes Rudern Kabel', 'Upright Row Cable']),
  E('frontziehen-turm-stange', 'Frontziehen am Turm mit Stange', 'Schulter', 'vordere Schulter', 'Kabelturm (Rolle unten), gerade Stange', { t: 'frontRaise', impl: 'cable' }, ['frontDelt'], ['sideDelt', 'upperBack'],
    'Mit dem Rücken zum Turm, Kabel läuft zwischen den Beinen. Stange mit Obergriff vor den Oberschenkeln.',
    'Stange mit fast gestreckten Armen nach vorne bis auf Schulterhöhe heben und langsam absenken.',
    'Bogen nach vorne-oben.',
    ['Rumpf stabil, kein Zurücklehnen', 'Konstante Kabelspannung'], ['Schwung', 'Zu hoch heben'], ['Frontheben Kabel']),
  E('frontziehen-kh-stehend', 'Frontziehen mit Kurzhantel – stehend', 'Schulter', 'vordere Schulter', 'Kurzhanteln', { t: 'frontRaise', impl: 'db' }, ['frontDelt'], ['sideDelt'],
    'Hüftbreiter Stand, Kurzhanteln vor den Oberschenkeln, Handflächen zum Körper.',
    'Arme mit leicht gebeugten Ellbogen nach vorne bis auf Schulterhöhe heben, kurz halten und langsam absenken.',
    'Bogen nach vorne-oben bis Schulterhöhe.',
    ['Auch abwechselnd möglich', 'Kein Schwung aus dem Rücken'], ['Zurücklehnen', 'Über Kopfhöhe heben'], ['Frontheben stehend', 'Front Raise']),
  E('frontheben-kh-sitzend', 'Frontheben mit Kurzhanteln – sitzend', 'Schulter', 'vordere Schulter', 'Kurzhanteln, Bank', { t: 'frontRaise', impl: 'db', seated: true }, ['frontDelt'], ['sideDelt'],
    'Aufrecht auf der Bank, Kurzhanteln seitlich vor dem Körper.',
    'Arme nach vorne bis Schulterhöhe heben und langsam absenken.',
    'Bogen nach vorne-oben.',
    ['Sitzend ist Schwung kaum möglich', 'Schultern tief halten'], ['Hohlkreuz', 'Zu schwer'], ['Frontheben sitzend']),
  E('nackenziehen-sz', 'Nackenziehen mit SZ-Stange', 'Schulter', 'seitliche Schulter & Trapez', 'SZ-Stange', { t: 'uprightRow', impl: 'ez' }, ['sideDelt', 'traps'], ['frontDelt', 'biceps'],
    'Hüftbreiter Stand, SZ-Stange mit Obergriff vor den Oberschenkeln.',
    'Stange eng am Körper bis Brusthöhe ziehen, Ellbogen hoch und außen. Kontrolliert absenken.',
    'Senkrecht am Körper nach oben.',
    ['SZ-Stange entlastet die Handgelenke', 'Nicht über Brusthöhe ziehen'], ['Zu enger Griff', 'Schwung aus den Beinen'], ['Aufrechtes Rudern', 'Upright Row']),
  E('shrugs-kh', 'Nackenshrugs mit Dumbbells', 'Schulter', 'Trapezmuskel (oben)', 'Kurzhanteln', { t: 'shrug' }, ['traps'], ['forearms'],
    'Aufrechter Stand, Kurzhanteln hängen seitlich, Arme gestreckt.',
    'Schultern senkrecht Richtung Ohren ziehen, kurz halten und langsam tief absenken.',
    'Senkrecht nach oben und unten – nicht kreisen.',
    ['Arme bleiben gestreckt', 'Kopf neutral', 'Volle Bewegung nach unten'], ['Schultern kreisen', 'Arme beugen', 'Kopf nach vorne'], ['Shrugs', 'Schulterheben']),
  E('schulterpresse-maschine', 'Schulterpressmaschine', 'Schulter', 'vordere & seitliche Schulter', 'Schulterpresse', { t: 'ohp', impl: 'machine', seated: true }, ['frontDelt', 'sideDelt'], ['triceps'],
    'Sitz so einstellen, dass die Griffe auf Schulterhöhe sind. Rücken an der Lehne.',
    'Griffe senkrecht nach oben drücken bis die Arme fast gestreckt sind und kontrolliert zurückführen.',
    'Senkrecht nach oben (gerätegeführt).',
    ['Gute Übung für den Einstieg', 'Rücken bleibt an der Lehne'], ['Sitzhöhe falsch', 'Arme ganz durchdrücken'], ['Shoulder Press Machine']),
  E('seitheben-maschine', 'Seithebenmaschine', 'Schulter', 'seitliche Schulter', 'Seitheben-Maschine', { t: 'lateral', machine: true }, ['sideDelt'], ['traps'],
    'Sitz so einstellen, dass das Schultergelenk auf Höhe der Drehachse liegt. Arme an den Polstern.',
    'Arme seitlich bis Schulterhöhe heben und langsam absenken.',
    'Seitlich nach oben (gerätegeführt).',
    ['Drehachse = Schultergelenk', 'Schultern tief'], ['Schultern ziehen hoch', 'Schwung'], ['Lateral Raise Machine']),
  E('reverse-butterfly', 'Butterfly-Reverse-Maschine – hintere Schulter', 'Schulter', 'hintere Schulter', 'Butterfly-Maschine (umgekehrt)', { t: 'fly', v: 'reverse' }, ['rearDelt'], ['upperBack', 'traps'],
    'Mit der Brust zum Polster sitzen, Griffe auf Schulterhöhe vor dem Körper, Arme fast gestreckt.',
    'Arme waagerecht nach außen-hinten führen, kurz halten, kontrolliert zurück.',
    'Waagerechter Bogen nach hinten.',
    ['Brust bleibt am Polster', 'Arme auf Schulterhöhe'], ['Schulterblätter zu stark zusammen (Rücken statt Schulter)', 'Schwung'], ['Reverse Butterfly', 'Reverse Pec Deck']),

  /* ---------------- RÜCKEN ---------------- */
  E('latziehen-breit', 'Latziehen – breiter Griff', 'Rücken', 'Latissimus', 'Latzugmaschine', { t: 'latPull' }, ['lats'], ['biceps', 'upperBack', 'rearDelt'],
    'Oberschenkel unter den Polstern fixiert, Stange breit im Obergriff, Arme gestreckt, Oberkörper leicht zurückgelehnt.',
    'Stange zur oberen Brust ziehen, Ellbogen nach unten-hinten, Brust raus. Kontrolliert nach oben führen, bis die Arme gestreckt sind.',
    'Senkrecht zur oberen Brust.',
    ['Erst Schulterblätter nach unten ziehen, dann Arme beugen', 'Oberkörper bleibt ruhig'], ['Stange in den Nacken ziehen', 'Starkes Zurücklehnen mit Schwung'], ['Latziehen', 'Lat Pulldown', 'Latzug']),
  E('klimmzuege', 'Klimmzüge', 'Rücken', 'Latissimus', 'Klimmzugstange', { t: 'latPull', v: 'pullup' }, ['lats'], ['biceps', 'upperBack', 'forearms'],
    'An der Stange hängend, Griff etwas breiter als schulterbreit, Arme fast gestreckt, Körper ruhig.',
    'Brust Richtung Stange ziehen, bis das Kinn über der Stange ist. Kontrolliert ablassen.',
    'Senkrecht nach oben.',
    ['Schulterblätter zuerst nach unten', 'Kein Schwung', 'Volle Bewegung'], ['Kipping/Schwung', 'Nur halbe Wiederholungen'], ['Klimmzug', 'Pull-ups', 'Pull Up']),
  E('lh-rudern', 'Langhantelrudern – normaler Griff', 'Rücken', 'Latissimus & oberer Rücken', 'Langhantel', { t: 'row', v: 'bar' }, ['lats', 'upperBack'], ['rearDelt', 'biceps', 'lowerBack'],
    'Schulterbreiter Stand, Knie gebeugt, Oberkörper mit geradem Rücken etwa 45° vorgebeugt. Stange im Obergriff, Arme gestreckt.',
    'Stange zum Bauchnabel ziehen, Ellbogen nach hinten, Schulterblätter zusammen. Kontrolliert ablassen.',
    'Nach oben-hinten zum Bauch.',
    ['Rücken bleibt neutral', 'Oberkörperwinkel bleibt gleich'], ['Rundrücken', 'Aufrichten mit Schwung'], ['Langhantelrudern', 'Barbell Row', 'Rudern', 'Rudern vorgebeugt']),
  E('lh-rudern-untergriff', 'Langhantelrudern – Umkehrgriff', 'Rücken', 'unterer Latissimus', 'Langhantel', { t: 'row', v: 'under' }, ['lats', 'upperBack'], ['biceps', 'lowerBack'],
    'Wie Langhantelrudern, aber Untergriff (Handflächen nach vorne), etwa schulterbreit.',
    'Stange zum unteren Bauch ziehen, Ellbogen eng am Körper. Kontrolliert ablassen.',
    'Nach oben-hinten zum Unterbauch.',
    ['Ellbogen eng', 'Handgelenke gerade'], ['Bizeps übernimmt', 'Rundrücken'], ['Yates Row', 'Rudern Untergriff']),
  E('kh-rudern-einarmig', 'Einarmiges Kurzhantelrudern', 'Rücken', 'Latissimus', 'Kurzhantel, Flachbank', { t: 'row', v: 'db1' }, ['lats', 'upperBack'], ['rearDelt', 'biceps'],
    'Ein Knie und die gleiche Hand auf der Bank, anderer Fuß am Boden. Rücken waagerecht und gerade, Kurzhantel hängt.',
    'Hantel Richtung Hüfte ziehen, Ellbogen nah am Körper. Kontrolliert ablassen. Danach Seite wechseln.',
    'Nach oben-hinten zur Hüfte.',
    ['Rumpf nicht aufdrehen', 'Volle Dehnung unten'], ['Oberkörper dreht mit', 'Ruckartiges Ziehen'], ['Kurzhantelrudern', 'One Arm Row']),
  E('kh-rudern-schraegbank', 'Beidarmiges Kurzhantelrudern auf der Schrägbank', 'Rücken', 'oberer Rücken & Latissimus', 'Kurzhanteln, Schrägbank', { t: 'row', v: 'dbIncline' }, ['upperBack', 'lats'], ['rearDelt', 'biceps'],
    'Mit der Brust auf einer Schrägbank (ca. 30–45°), Füße am Boden. Kurzhanteln hängen.',
    'Beide Hanteln nach oben ziehen, Schulterblätter zusammen. Kontrolliert ablassen.',
    'Senkrecht nach oben.',
    ['Brust bleibt am Polster', 'Entlastet den unteren Rücken'], ['Brust löst sich', 'Kopf überstreckt'], ['Chest Supported Row']),
  E('t-bar-rudern', 'T-Bar-Rudern', 'Rücken', 'mittlerer Rücken', 'T-Bar (Langhantel in Landmine) mit Griff', { t: 'row', v: 'tbar' }, ['upperBack', 'lats'], ['rearDelt', 'biceps', 'lowerBack'],
    'Über der Stange stehend, Knie gebeugt, Rücken gerade vorgebeugt. Enger Griff unter der Brust.',
    'Griff Richtung Brust/Bauch ziehen, Schulterblätter zusammen, kontrolliert ablassen.',
    'Bogen nach oben-hinten.',
    ['Rücken neutral', 'Brust raus'], ['Rundrücken', 'Aufrichten mit Schwung'], ['T-Bar Row']),
  E('rudermaschine-breit', 'Rudermaschine – breiter Griff', 'Rücken', 'oberer Rücken', 'Rudermaschine', { t: 'row', v: 'machineWide' }, ['upperBack', 'rearDelt'], ['lats', 'biceps'],
    'Brust am Polster, Sitz so einstellen, dass die Griffe auf Schulterhöhe sind. Breiter Griff, Arme gestreckt.',
    'Griffe mit hohen Ellbogen nach hinten ziehen, Schulterblätter zusammen. Kontrolliert strecken.',
    'Waagerecht nach hinten.',
    ['Brust bleibt am Polster', 'Ellbogen auf Schulterhöhe'], ['Schultern ziehen hoch', 'Oberkörper lehnt zurück'], ['Rudermaschine']),
  E('rudern-eng-turm', 'Rudermaschine – enger Griff am Turm', 'Rücken', 'Latissimus & mittlerer Rücken', 'Kabelrudern (tief), V-Griff', { t: 'row', v: 'cableNarrow' }, ['lats', 'upperBack'], ['biceps', 'lowerBack'],
    'Auf der Bank, Füße auf der Plattform, Knie leicht gebeugt. V-Griff, Arme gestreckt, Rücken gerade.',
    'Griff zum Bauch ziehen, Ellbogen eng am Körper, Brust raus. Kontrolliert nach vorne strecken.',
    'Waagerecht zum Bauch.',
    ['Oberkörper bewegt sich nur minimal', 'Schulterblätter zusammen'], ['Starkes Vor- und Zurückschwingen', 'Rundrücken'], ['Kabelrudern', 'Seated Cable Row', 'Rudern am Kabel']),
  E('t-bar-maschine', 'T-Bar-Maschine – Rücken', 'Rücken', 'mittlerer Rücken', 'T-Bar-Rudermaschine mit Brustpolster', { t: 'row', v: 'tbarMachine' }, ['upperBack', 'lats'], ['rearDelt', 'biceps'],
    'Brust auf dem schrägen Polster, Füße auf der Plattform, Griffe hängen mit gestreckten Armen.',
    'Griffe nach oben ziehen, Schulterblätter zusammen, kontrolliert ablassen.',
    'Nach oben-hinten.',
    ['Brust bleibt am Polster', 'Volle Dehnung unten'], ['Schwung', 'Kopf überstreckt'], ['T-Bar Maschine']),
  E('rueckenstrecker-tension', 'Rückenstrecker an der Tension Bank', 'Rücken', 'unterer Rücken', 'Hyperextensionsbank (45°)', { t: 'backExt' }, ['lowerBack', 'glutes'], ['hamstrings'],
    'Hüfte auf dem Polster, Füße unter der Rolle fixiert, Arme vor der Brust verschränkt. Oberkörper hängt nach unten.',
    'Oberkörper mit geradem Rücken anheben, bis Körper und Beine eine Linie bilden. Kontrolliert absenken.',
    'Bogen um die Hüfte nach oben.',
    ['Nicht überstrecken', 'Bewegung aus der Hüfte'], ['Hohlkreuz am Ende', 'Ruckartige Bewegung'], ['Rückenstrecker', 'Hyperextensions', 'Back Extension']),
  E('ueberzuege-turm', 'Überzüge am Turm – Rücken / Dehnung', 'Rücken', 'Latissimus', 'Kabelturm (Rolle oben), Stange', { t: 'pullover', v: 'cable' }, ['lats'], ['triceps', 'abs'],
    'Vor dem Turm, leicht in der Hüfte vorgebeugt. Stange mit gestreckten Armen schräg über dem Kopf.',
    'Stange mit gestreckten Armen im Bogen bis zu den Oberschenkeln ziehen. Kontrolliert zurück nach oben in die Dehnung.',
    'Bogen von oben nach unten vor dem Körper.',
    ['Arme bleiben gestreckt', 'Rumpf stabil'], ['Arme beugen', 'Oberkörper pumpt mit'], ['Straight Arm Pulldown', 'Kabelüberzüge']),

  /* ---------------- BEINE ---------------- */
  E('kniebeuge', 'Kniebeuge / Back Squat', 'Beine', 'Quadrizeps & Gesäß', 'Langhantel, Rack', { t: 'squat', v: 'back' }, ['quads', 'glutes'], ['adductors', 'hamstrings', 'lowerBack', 'abs'],
    'Stange auf dem oberen Trapez, Füße schulterbreit, Fußspitzen leicht nach außen. Brust raus, Rumpf fest.',
    'Hüfte nach hinten-unten, Knie in Richtung Zehen. Absenken, bis die Oberschenkel etwa parallel sind. Über die ganze Fußsohle hochdrücken.',
    'Senkrecht über der Fußmitte.',
    ['Fersen bleiben am Boden', 'Knie folgen den Zehen', 'Rücken neutral'], ['Knie fallen nach innen', 'Fersen heben ab', 'Rundrücken in der Tiefe'], ['Kniebeugen', 'Squat', 'Back Squat']),
  E('frontkniebeuge', 'Frontkniebeuge', 'Beine', 'Quadrizeps', 'Langhantel, Rack', { t: 'squat', v: 'front' }, ['quads'], ['glutes', 'abs', 'upperBack'],
    'Stange vorne auf den Schultern, Ellbogen hoch nach vorne. Füße schulterbreit.',
    'Aufrecht nach unten in die Hocke gehen, Ellbogen bleiben oben. Kraftvoll hochdrücken.',
    'Senkrecht, Oberkörper sehr aufrecht.',
    ['Ellbogen hoch – sonst rollt die Stange', 'Aufrechter als bei der Back Squat'], ['Ellbogen sinken', 'Oberkörper kippt nach vorne'], ['Front Squat']),
  E('ausfallschritte-gehen', 'Ausfallschritte im Gehen', 'Beine', 'Quadrizeps & Gesäß', 'Körpergewicht oder Kurzhanteln', { t: 'lunge', v: 'walk' }, ['quads', 'glutes'], ['hamstrings', 'adductors', 'calves'],
    'Aufrechter Stand, Kurzhanteln seitlich (optional).',
    'Großen Schritt nach vorne, senkrecht absenken bis das hintere Knie knapp über dem Boden ist. Über das vordere Bein hochdrücken und mit dem hinteren Bein den nächsten Schritt machen.',
    'Vorwärts, abwechselnd links und rechts.',
    ['Oberkörper aufrecht', 'Vorderes Knie über dem Fuß'], ['Zu kurze Schritte', 'Knie fällt nach innen'], ['Walking Lunges', 'Ausfallschritte gehend']),
  E('ausfallschritte-lh', 'Ausfallschritte stehend mit Langhantel auf dem Nacken', 'Beine', 'Quadrizeps & Gesäß', 'Langhantel', { t: 'lunge', v: 'bar' }, ['quads', 'glutes'], ['hamstrings', 'abs'],
    'Stange auf dem oberen Rücken, Schrittstellung mit hüftbreiter Spur.',
    'Senkrecht absenken, bis das hintere Knie knapp über dem Boden ist. Über die vordere Ferse hochdrücken.',
    'Senkrecht nach unten und oben.',
    ['Spurbreite hüftbreit für Balance', 'Gewicht auf dem vorderen Bein'], ['Oberkörper kippt', 'Zu schmale Spur'], ['Ausfallschritte Langhantel', 'Barbell Lunge']),
  E('ausfallschritte-einbeinig-kh', 'Ausfallschritte einbeinig mit Dumbbells', 'Beine', 'Quadrizeps & Gesäß', 'Kurzhanteln', { t: 'lunge', v: 'db' }, ['quads', 'glutes'], ['hamstrings', 'adductors'],
    'Schrittstellung, Kurzhanteln seitlich. Alle Wiederholungen zuerst auf einer Seite.',
    'Senkrecht absenken und über das vordere Bein hochdrücken. Danach Seite wechseln.',
    'Senkrecht nach unten und oben.',
    ['Rumpf aufrecht', 'Kontrolliert ohne Abfedern'], ['Vorderes Knie schiebt weit nach vorne', 'Schwanken'], ['Split Squat']),
  E('beinpresse', 'Beinpresse', 'Beine', 'Quadrizeps & Gesäß', 'Beinpresse (45°)', { t: 'legPress' }, ['quads', 'glutes'], ['hamstrings', 'adductors'],
    'Rücken und Gesäß fest am Polster, Füße hüftbreit mittig auf der Plattform, Beine fast gestreckt.',
    'Plattform kontrolliert ablassen bis etwa 90° Kniewinkel. Über die ganze Sohle wegdrücken, Knie nicht durchstrecken.',
    'Entlang der Schienen schräg.',
    ['Gesäß bleibt am Polster', 'Knie in Zehenrichtung'], ['Zu tief – Becken rollt ein', 'Knie durchdrücken'], ['Leg Press', 'Beinpresse 45']),
  E('hackenschmidt', 'Hackenschmidt-Maschine', 'Beine', 'Quadrizeps', 'Hackenschmidt-Maschine', { t: 'squat', v: 'hack' }, ['quads'], ['glutes', 'adductors'],
    'Rücken am Polster, Schultern unter den Pads, Füße schulterbreit auf der Plattform.',
    'Kontrolliert in die Knie gehen bis ca. 90°, dann über die ganze Sohle hochdrücken.',
    'Entlang der Führungsschienen.',
    ['Fußposition: weiter vorne = mehr Gesäß', 'Knie nicht durchstrecken'], ['Fersen heben ab', 'Rücken löst sich'], ['Hack Squat', 'Hackenschmidt']),
  E('beinbeuger-maschine', 'Beinbeugermaschine', 'Beine', 'Beinbeuger', 'Beinbeuger-Maschine (liegend)', { t: 'legCurl' }, ['hamstrings'], ['calves'],
    'Bauchlage, Knie knapp hinter der Polsterkante, Rolle über den Fersen. Griffe halten.',
    'Fersen Richtung Gesäß beugen, kurz halten, langsam strecken.',
    'Bogen um das Knie.',
    ['Hüfte bleibt am Polster', 'Langsame exzentrische Phase'], ['Hüfte hebt ab', 'Schwung'], ['Beinbeuger', 'Leg Curl']),
  E('beinstrecker-maschine', 'Beinstreckermaschine', 'Beine', 'Quadrizeps', 'Beinstrecker-Maschine', { t: 'legExt' }, ['quads'], [],
    'Rücken an der Lehne, Kniegelenk auf Höhe der Drehachse, Polster vorne über dem Sprunggelenk.',
    'Beine strecken, kurz anspannen, langsam beugen.',
    'Bogen um das Knie nach vorne-oben.',
    ['Drehachse = Kniegelenk', 'Oben kurz halten'], ['Schwung', 'Gesäß hebt ab'], ['Beinstrecker', 'Leg Extension']),
  E('hip-thrust', 'Hip Thrust', 'Beine', 'Gesäß', 'Langhantel (mit Polster), Bank', { t: 'hipThrust' }, ['glutes'], ['hamstrings', 'quads'],
    'Schulterblätter an der Bankkante, Füße hüftbreit am Boden, Stange auf der Hüftbeuge.',
    'Hüfte nach oben strecken, bis Oberkörper und Oberschenkel eine Linie bilden. Kurz anspannen, kontrolliert absenken.',
    'Senkrecht nach oben, um die Schulterblätter als Drehpunkt.',
    ['Oben Kinn leicht zur Brust', 'Schienbeine oben senkrecht'], ['Hohlkreuz oben', 'Füße zu weit weg'], ['Hip Thrusts', 'Hüftheben']),
  E('kickbacks-turm', 'Kickbacks am Turm', 'Beine', 'Gesäß', 'Kabelturm (Rolle unten), Fußschlaufe', { t: 'kickback' }, ['glutes'], ['hamstrings'],
    'Vor dem Turm, Schlaufe am Fuß, Hände am Turm, Oberkörper leicht vorgeneigt, Standbein leicht gebeugt.',
    'Arbeitsbein gestreckt nach hinten-oben führen, Gesäß anspannen, kontrolliert zurück.',
    'Bogen nach hinten.',
    ['Becken bleibt gerade', 'Kein Hohlkreuz'], ['Schwung', 'Becken dreht auf'], ['Cable Kickbacks', 'Kickbacks']),
  E('adduktoren-maschine', 'Adduktorenmaschine', 'Beine', 'Adduktoren', 'Adduktoren-Maschine', { t: 'adAb', v: 'ad' }, ['adductors'], [],
    'Rücken an der Lehne, Polster innen an den Knien, Beine geöffnet.',
    'Beine gegen den Widerstand schließen, kurz halten, langsam öffnen.',
    'Seitlich nach innen.',
    ['Nur so weit öffnen, wie es angenehm ist'], ['Schwung', 'Gewicht zuschlagen lassen'], ['Adduktoren', 'Adduktor']),
  E('abduktoren-maschine', 'Abduktorenmaschine', 'Beine', 'Abduktoren / seitliches Gesäß', 'Abduktoren-Maschine', { t: 'adAb', v: 'ab' }, ['abductors', 'glutes'], [],
    'Rücken an der Lehne, Polster außen an den Knien, Beine geschlossen.',
    'Beine gegen den Widerstand nach außen drücken, kurz halten, langsam schließen.',
    'Seitlich nach außen.',
    ['Leicht vorgeneigt betont das Gesäß mehr'], ['Schwung', 'Zu kleine Bewegung'], ['Abduktoren', 'Abduktor']),
  E('wadenheben-sitzend', 'Wadenheben sitzend', 'Beine', 'Waden (Schollenmuskel)', 'Wadenmaschine sitzend', { t: 'calf', v: 'seated' }, ['calves'], [],
    'Sitzend, Polster auf den Oberschenkeln knapp über dem Knie, Fußballen auf der Kante.',
    'Fersen tief absenken (Dehnung), dann so hoch wie möglich drücken. Kurz halten.',
    'Senkrecht.',
    ['Volle Bewegungsamplitude', 'Langsam'], ['Wippen', 'Halbe Wiederholungen'], ['Seated Calf Raise']),
  E('wadenheben-stehend', 'Wadenheben stehend', 'Beine', 'Waden', 'Wadenmaschine stehend / Stufe', { t: 'calf', v: 'standing' }, ['calves'], [],
    'Fußballen auf der Kante, Beine gestreckt, Schultern unter den Polstern.',
    'Fersen tief absenken, dann maximal hochdrücken, kurz halten.',
    'Senkrecht.',
    ['Knie gestreckt, aber nicht überstreckt', 'Oben kurz halten'], ['Wippen', 'Knie beugen'], ['Calf Raise', 'Wadenheben']),
  E('frontkniebeuge-kh', 'Frontkniebeuge mit Kurzhantel', 'Beine', 'Quadrizeps & Gesäß', 'Kurzhantel', { t: 'squat', v: 'goblet' }, ['quads', 'glutes'], ['adductors', 'abs'],
    'Kurzhantel senkrecht vor der Brust (Goblet-Haltung), Füße schulterbreit.',
    'Aufrecht in die tiefe Hocke gehen, Ellbogen zwischen die Knie. Hochdrücken.',
    'Senkrecht.',
    ['Sehr gute Technikübung', 'Brust bleibt oben'], ['Rundrücken', 'Fersen heben ab'], ['Goblet Squat']),
  E('frontkniebeuge-kh-eng', 'Sehr enge Frontkniebeuge mit Kurzhantel – Quadriceps-Fokus', 'Beine', 'Quadrizeps', 'Kurzhantel', { t: 'squat', v: 'narrow' }, ['quads'], ['glutes'],
    'Füße sehr eng (fast geschlossen), Kurzhantel vor der Brust.',
    'Knie schieben weit nach vorne, Oberkörper sehr aufrecht, tief absenken. Hochdrücken.',
    'Senkrecht, Knie nach vorne.',
    ['Fersen ggf. leicht erhöht', 'Langsames Tempo'], ['Fersen heben ab', 'Knie fallen nach innen'], ['Narrow Goblet Squat']),

  /* ---------------- BAUCH ---------------- */
  E('crunches-turm', 'Crunches am Turm', 'Bauch', 'gerader Bauchmuskel', 'Kabelturm (Rolle oben), Seil', { t: 'crunchCable' }, ['abs'], ['obliques'],
    'Vor dem Turm knien, Seil neben dem Kopf halten.',
    'Oberkörper einrollen, Ellbogen Richtung Knie. Hüfte bleibt ruhig. Kontrolliert aufrollen.',
    'Einrollen nach vorne-unten.',
    ['Bewegung aus der Wirbelsäule, nicht aus der Hüfte', 'Ausatmen beim Einrollen'], ['Mit den Armen ziehen', 'Hüfte bewegt sich mit'], ['Kabelcrunches', 'Cable Crunch']),
  E('beinheben-liegend', 'Beinheben liegend', 'Bauch', 'unterer Bauch', 'Matte', { t: 'legRaise', v: 'lying' }, ['abs', 'hipFlexors'], [],
    'Rückenlage, Hände neben dem Gesäß, Beine gestreckt knapp über dem Boden.',
    'Beine gestreckt bis zur Senkrechten heben, langsam absenken ohne abzulegen.',
    'Bogen nach oben.',
    ['Unterer Rücken bleibt am Boden', 'Langsam absenken'], ['Hohlkreuz', 'Schwung'], ['Leg Raises', 'Beinheben']),
  E('beinheben-haengend', 'Beinheben hängend', 'Bauch', 'unterer Bauch', 'Klimmzugstange', { t: 'legRaise', v: 'hangKnee' }, ['abs', 'hipFlexors'], ['forearms'],
    'An der Stange hängend, Körper ruhig.',
    'Knie zur Brust ziehen, Becken leicht einrollen. Langsam absenken.',
    'Nach oben vorne.',
    ['Kein Schwung', 'Becken einrollen'], ['Schwingen', 'Nur Hüftbeugung'], ['Hanging Knee Raise', 'Knieheben hängend']),
  E('beinheben-haengend-gestreckt', 'Beinheben hängend – gestreckt', 'Bauch', 'unterer Bauch', 'Klimmzugstange', { t: 'legRaise', v: 'hangStraight' }, ['abs', 'hipFlexors'], ['forearms'],
    'An der Stange hängend, Beine gestreckt.',
    'Gestreckte Beine bis zur Waagerechten heben, langsam absenken.',
    'Bogen nach vorne-oben.',
    ['Sehr anspruchsvoll – ruhig ausführen'], ['Schwung', 'Knie beugen'], ['Hanging Leg Raise']),
  E('russian-twist', 'Russian Twist', 'Bauch', 'schräge Bauchmuskeln', 'Matte, Hantelscheibe (optional)', { t: 'russianTwist' }, ['obliques', 'abs'], ['hipFlexors'],
    'Sitzend, Oberkörper ca. 45° zurückgelehnt, Knie gebeugt, Füße leicht angehoben.',
    'Oberkörper abwechselnd nach links und rechts drehen, Gewicht neben die Hüfte führen.',
    'Rotation um die Körperlängsachse.',
    ['Rücken gerade', 'Drehung aus dem Oberkörper'], ['Rundrücken', 'Nur Arme bewegen'], ['Russian Twists']),

  /* ---------------- STABILISATION ---------------- */
  E('plank', 'Plank', 'Stabilisation', 'Rumpf', 'Matte', { t: 'plank' }, ['abs'], ['obliques', 'glutes', 'frontDelt'],
    'Unterarmstütz, Ellbogen unter den Schultern, Körper bildet eine gerade Linie.',
    'Position halten, Bauch und Gesäß anspannen, ruhig atmen.',
    'Statisch.',
    ['Becken weder hoch noch durchhängend', 'Blick zum Boden'], ['Hohlkreuz', 'Gesäß zu hoch'], ['Unterarmstütz', 'Planks']),
  E('plank-beinheben', 'Plank mit Beinheben', 'Stabilisation', 'Rumpf & Gesäß', 'Matte', { t: 'plank', v: 'leg' }, ['abs', 'glutes'], ['obliques'],
    'Unterarmstütz, Körper in einer Linie.',
    'Ein Bein gestreckt anheben, kurz halten, absenken, Seite wechseln.',
    'Bein nach oben.',
    ['Becken bleibt ruhig'], ['Becken dreht auf', 'Hohlkreuz'], []),
  E('seitstuetz-becken', 'Seitstütz mit Beckenheben und -senken', 'Stabilisation', 'seitlicher Rumpf', 'Matte', { t: 'plank', v: 'side' }, ['obliques'], ['abductors', 'abs'],
    'Seitlicher Unterarmstütz, Ellbogen unter der Schulter, Körper in einer Linie.',
    'Becken kontrolliert Richtung Boden senken und wieder hochdrücken.',
    'Becken senkrecht auf und ab.',
    ['Schulter stabil', 'Körper bleibt in einer Ebene'], ['Becken kippt nach vorne', 'Schulter sinkt ein'], ['Side Plank Hip Dips']),
  E('seitstuetz-bein', 'Seitstütz mit Beinheben', 'Stabilisation', 'seitlicher Rumpf & Gesäß', 'Matte', { t: 'plank', v: 'sideLeg' }, ['obliques', 'abductors'], ['glutes'],
    'Seitlicher Unterarmstütz, Körper in einer Linie.',
    'Oberes Bein gestreckt anheben und kontrolliert absenken.',
    'Bein seitlich nach oben.',
    ['Becken bleibt oben'], ['Becken sackt ab'], []),

  /* ---------------- ATHLETIK ---------------- */
  E('squat-jumps', 'Squat Jumps', 'Athletik', 'Beine, Explosivkraft', 'Körpergewicht', { t: 'jump', v: 'squat' }, ['quads', 'glutes', 'calves'], ['hamstrings'],
    'Hüftbreiter Stand.',
    'Tief in die Hocke, explosiv nach oben springen, Arme schwingen mit. Weich landen und direkt in die nächste Hocke.',
    'Senkrecht nach oben.',
    ['Weiche Landung über den Fußballen', 'Knie über den Zehen'], ['Harte Landung', 'Knie fallen nach innen'], ['Sprungkniebeugen', 'Jump Squats']),
  E('box-jumps', 'Box Jumps', 'Athletik', 'Beine, Explosivkraft', 'Plyo-Box', { t: 'jump', v: 'box' }, ['quads', 'glutes', 'calves'], ['hamstrings'],
    'Vor der Box, hüftbreiter Stand.',
    'Ausholen, explosiv auf die Box springen, weich landen und aufrichten. Kontrolliert herabsteigen.',
    'Nach vorne-oben.',
    ['Herabsteigen statt springen schont die Gelenke', 'Boxhöhe passend wählen'], ['Zu hohe Box', 'Harte Landung'], ['Boxsprünge']),
  E('knee-tuck-jumps', 'Hoch-Tief-Sprünge / Knee-Tuck-Jumps', 'Athletik', 'Beine & Bauch, Explosivkraft', 'Körpergewicht', { t: 'jump', v: 'tuck' }, ['quads', 'hipFlexors', 'calves'], ['abs', 'glutes'],
    'Hüftbreiter Stand.',
    'Kurz ausholen, explosiv springen und die Knie zur Brust ziehen. Weich landen.',
    'Senkrecht nach oben.',
    ['Kurze Bodenkontaktzeit', 'Rumpf stabil'], ['Harte Landung', 'Rundrücken in der Luft'], ['Tuck Jumps']),
  E('jumping-lunges', 'Ausfallschritte im Sprung / Jumping Lunges', 'Athletik', 'Beine, Explosivkraft', 'Körpergewicht', { t: 'jump', v: 'lungeJump' }, ['quads', 'glutes'], ['calves', 'hamstrings'],
    'Ausfallschrittposition.',
    'Explosiv abspringen, in der Luft die Beine wechseln, weich im Ausfallschritt landen.',
    'Senkrecht, Beine wechseln.',
    ['Oberkörper aufrecht', 'Weich landen'], ['Knie knallt auf den Boden', 'Zu kurze Schritte'], ['Jump Lunges']),
  E('mountain-climbers', 'Mountain Climbers', 'Athletik', 'Rumpf & Kondition', 'Körpergewicht', { t: 'jump', v: 'mountain' }, ['abs', 'hipFlexors'], ['frontDelt', 'quads'],
    'Liegestützposition, Hände unter den Schultern.',
    'Knie abwechselnd schnell zur Brust ziehen, Hüfte bleibt tief.',
    'Knie nach vorne, abwechselnd.',
    ['Schultern über den Händen', 'Becken nicht hochschieben'], ['Gesäß zu hoch', 'Hüpfen statt Laufen'], ['Bergsteiger']),
  E('seitliche-spruenge', 'Seitliche Sprünge', 'Athletik', 'Beine, Koordination', 'Körpergewicht (Linie am Boden)', { t: 'jump', v: 'lateral' }, ['calves', 'quads'], ['abductors', 'glutes'],
    'Neben einer Linie, Füße zusammen, Knie leicht gebeugt.',
    'Schnell seitlich über die Linie hin und her springen, weich landen.',
    'Seitlich links – rechts.',
    ['Kurzer Bodenkontakt', 'Oberkörper ruhig'], ['Zu große, unkontrollierte Sprünge'], ['Lateral Jumps', 'Seitsprünge']),
  E('seitliche-squat-jumps', 'Seitliche Squat Jumps', 'Athletik', 'Beine, Explosivkraft & Koordination', 'Körpergewicht', { t: 'jump', v: 'latSquat' }, ['quads', 'glutes', 'abductors'], ['calves', 'adductors'],
    'Mitte, tiefe Hocke, Füße etwas breiter als hüftbreit.',
    'Explosiv nach rechts springen und in der Hocke landen, zurück zur Mitte, dann nach links, zurück zur Mitte und erneut nach rechts.',
    'Mitte → rechts → Mitte → links → Mitte → rechts …',
    ['Jede Landung weich in der Hocke abfangen', 'Knie über den Zehen'], ['Landung mit gestreckten Beinen', 'Knie fallen nach innen'], ['Squat-Sprünge seitlich', 'Squat-Sprünge gerade rechts'])
  ];
  window.SW_KATALOG = L;
})();
